### ISSUE TITLE
install script install-0.1.0.php

### ISSUE THREAD

**Issue by kevinjavitz** [amacgregor/mdg_giftreg#2]
lines 44 - 139 and 140 - 236 are repeats trying to make the same table twice, hopefully is not me being dumb or missing something :)

**Comment by amacgregor** [comment]
No, its me being dumb ;) will correct the issue

**Comment by amacgregor** [comment]
Issue corrected, sorry it too so long. I'll be fixing all the code issues and finishing the extra content in the couple of weeks. Please check the chapter4 branch for the update code

https://github.com/amacgregor/mdg_giftreg/tree/chapter4
