### ISSUE TITLE
Chapter 4, deleteAction does not check ownership

### ISSUE THREAD

**Issue by nubeiro** [amacgregor/mdg_giftreg#5]
I've finished chapter 4 and I do not find any references to checking registry ownership before deletion. So if a customer is logged in and tries a GET request to the delete action with some random registry id, it will get deleted?

Taken from https://github.com/amacgregor/mdg_giftreg/blob/chapter5/app/code/local/Mdg/Giftregistry/controllers/IndexController.php#L20

Shouldn't there be some kind of server side validation before deleting a registry?
- is $registry_id a valid id?
- if it is ... does it belong to the logged in customer?

**Comment by amacgregor** [comment]
Thanks for the feedback I will make sure this gets updated for the upcoming version of the book
