### ISSUE TITLE
Stuck in Chapter 4

### ISSUE THREAD

**Issue by davidangel** [amacgregor/mdg_giftreg#7]
I'm stuck in chapter 4. Is there a branch with all of the code in a completed form that I could check against? Thanks!

**Comment by amacgregor** [comment]
Hi David, 

Apologies for the very late reply is there a specific issue that I could help with?

**Comment by davidangel** [comment]
No there is not. I have moved on. I'm de-recommending that the book be used in our on boarding process.----------
David Angel
david@davidangel.net
865-599-5614
